version: "3"
services:
  frontend:
    container_name: frontend
    build: .
    restart: unless-stopped
    env_file: .env
    environment:
      STRAPI_URL: ${STRAPI_URL}
    ports:
      - "80:80"
